sudo: required

language: scala

scala:
  - 2.11.7
  - 2.10.6

jdk:
  - oraclejdk8
  - openjdk6

script:
    - sbt ++$TRAVIS_SCALA_VERSION download-database test

# cf. https://github.com/travis-ci/travis-ci/issues/5227
before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

